// Sub-Saharan Africa: ISO code, name, dial code. Mirrors app/src/countries.ts —
// keep both lists in step. Extend when North Africa launches.
export const COUNTRIES = [
  { code: 'NG', name: 'Nigeria', dial: '234' },
  { code: 'GH', name: 'Ghana', dial: '233' },
  { code: 'KE', name: 'Kenya', dial: '254' },
  { code: 'ZA', name: 'South Africa', dial: '27' },
  { code: 'UG', name: 'Uganda', dial: '256' },
  { code: 'TZ', name: 'Tanzania', dial: '255' },
  { code: 'RW', name: 'Rwanda', dial: '250' },
  { code: 'SN', name: 'Senegal', dial: '221' },
  { code: 'CI', name: "Côte d'Ivoire", dial: '225' },
  { code: 'CM', name: 'Cameroon', dial: '237' },
  { code: 'ET', name: 'Ethiopia', dial: '251' },
  { code: 'CD', name: 'DR Congo', dial: '243' },
  { code: 'CG', name: 'Congo (Republic)', dial: '242' },
  { code: 'GA', name: 'Gabon', dial: '241' },
  { code: 'GQ', name: 'Equatorial Guinea', dial: '240' },
  { code: 'ST', name: 'São Tomé and Príncipe', dial: '239' },
  { code: 'AO', name: 'Angola', dial: '244' },
  { code: 'NA', name: 'Namibia', dial: '264' },
  { code: 'BW', name: 'Botswana', dial: '267' },
  { code: 'ZW', name: 'Zimbabwe', dial: '263' },
  { code: 'ZM', name: 'Zambia', dial: '260' },
  { code: 'MW', name: 'Malawi', dial: '265' },
  { code: 'MZ', name: 'Mozambique', dial: '258' },
  { code: 'MG', name: 'Madagascar', dial: '261' },
  { code: 'MU', name: 'Mauritius', dial: '230' },
  { code: 'SC', name: 'Seychelles', dial: '248' },
  { code: 'KM', name: 'Comoros', dial: '269' },
  { code: 'SO', name: 'Somalia', dial: '252' },
  { code: 'DJ', name: 'Djibouti', dial: '253' },
  { code: 'ER', name: 'Eritrea', dial: '291' },
  { code: 'SS', name: 'South Sudan', dial: '211' },
  { code: 'SD', name: 'Sudan', dial: '249' },
  { code: 'TD', name: 'Chad', dial: '235' },
  { code: 'CF', name: 'Central African Republic', dial: '236' },
  { code: 'NE', name: 'Niger', dial: '227' },
  { code: 'ML', name: 'Mali', dial: '223' },
  { code: 'BF', name: 'Burkina Faso', dial: '226' },
  { code: 'TG', name: 'Togo', dial: '228' },
  { code: 'BJ', name: 'Benin', dial: '229' },
  { code: 'GM', name: 'Gambia', dial: '220' },
  { code: 'GW', name: 'Guinea-Bissau', dial: '245' },
  { code: 'GN', name: 'Guinea', dial: '224' },
  { code: 'SL', name: 'Sierra Leone', dial: '232' },
  { code: 'LR', name: 'Liberia', dial: '231' },
  { code: 'MR', name: 'Mauritania', dial: '222' },
  { code: 'CV', name: 'Cabo Verde', dial: '238' },
  { code: 'LS', name: 'Lesotho', dial: '266' },
  { code: 'SZ', name: 'Eswatini', dial: '268' },
  { code: 'BI', name: 'Burundi', dial: '257' },
];
